//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.05 at 02:17:50 PM MSK 
//


package Dance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DanceGroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DanceGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DanceGroupName" type="{}NameOfDanceGroup"/>
 *         &lt;element name="YearOfFoundation" type="{}YearOfFoundation"/>
 *         &lt;element name="FounderName" type="{}NameOfFounder"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DanceGroup", propOrder = {
        "danceGroupName",
        "yearOfFoundation",
        "founderName"
})
public class DanceGroup {

    @XmlElement(name = "DanceGroupName", required = true)
    protected String danceGroupName;
    @XmlElement(name = "YearOfFoundation")
    @XmlSchemaType(name = "integer")
    protected int yearOfFoundation;
    @XmlElement(name = "FounderName", required = true)
    protected String founderName;

    /**
     * Gets the value of the danceGroupName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDanceGroupName() {
        return danceGroupName;
    }

    /**
     * Sets the value of the danceGroupName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDanceGroupName(String value) {
        this.danceGroupName = value;
    }

    /**
     * Gets the value of the yearOfFoundation property.
     */
    public int getYearOfFoundation() {
        return yearOfFoundation;
    }

    /**
     * Sets the value of the yearOfFoundation property.
     */
    public void setYearOfFoundation(int value) {
        this.yearOfFoundation = value;
    }

    /**
     * Gets the value of the founderName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFounderName() {
        return founderName;
    }

    /**
     * Sets the value of the founderName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFounderName(String value) {
        this.founderName = value;
    }

    @Override
    public String toString() {
        return "DanceGroup{" +
                "danceGroupName='" + danceGroupName + '\'' +
                ", yearOfFoundation=" + yearOfFoundation +
                ", founderName='" + founderName + '\'' +
                '}';
    }
}
