//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.05 at 02:55:58 PM MSK 
//


package Dance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PairTypeDancer_QNAME = new QName("", "Dancer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SomeDances }
     */
    public SomeDances createSomeDances() {
        return new SomeDances();
    }

    /**
     * Create an instance of {@link Dance }
     */
    public Dance createDance() {
        return new Dance();
    }

    /**
     * Create an instance of {@link PairType }
     */
    public PairType createPairType() {
        return new PairType();
    }

    /**
     * Create an instance of {@link Dancer }
     */
    public Dancer createDancer() {
        return new Dancer();
    }

    /**
     * Create an instance of {@link SoloPairGroup }
     */
    public SoloPairGroup createSoloPairGroup() {
        return new SoloPairGroup();
    }

    /**
     * Create an instance of {@link DanceGroup }
     */
    public DanceGroup createDanceGroup() {
        return new DanceGroup();
    }

    /**
     * Create an instance of {@link SoloType }
     */
    public SoloType createSoloType() {
        return new SoloType();
    }

    /**
     * Create an instance of {@link MassType }
     */
    public MassType createMassType() {
        return new MassType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dancer }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Dancer", scope = PairType.class)
    public JAXBElement<Dancer> createPairTypeDancer(Dancer value) {
        return new JAXBElement<Dancer>(_PairTypeDancer_QNAME, Dancer.class, PairType.class, value);
    }

}
